<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Peserta;

class PesertaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nuptk'         => '1234567890123456',
                'tanggal_lahir' => '1990-05-15',
                'nama'          => 'Amara Putri',
                'sekolah'       => 'SMA Negeri 1 Jakarta',
                'email'         => 'amara@gmail.com',
                'kota'          => 'Jakarta',
                'provinsi'      => 'DKI Jakarta',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '9876543210987654',
                'tanggal_lahir' => '1988-11-20',
                'nama'          => 'Siti Rahayu',
                'sekolah'       => 'SMP Negeri 3 Bandung',
                'email'         => 'siti@gmail.com',
                'kota'          => 'Bandung',
                'provinsi'      => 'Jawa Barat',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '1112223334445556',
                'tanggal_lahir' => '2000-02-01',
                'nama'          => 'Rachel',
                'sekolah'       => 'SMA Citra Bangsa',
                'email'         => 'rachel@gmail.com',
                'kota'          => 'Jakarta',
                'provinsi'      => 'DKI Jakarta',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
    'nuptk'         => '1501040400000004',
    'tanggal_lahir' => '1991-06-23',
    'nama'          => 'Fajar Nugroho',
    'sekolah'       => 'SMA Negeri 1 Palembang',
    'email'         => 'fajar.nugroho@gmail.com',
    'kota'          => 'Palembang',
    'provinsi'      => 'Sumatera Selatan',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '6101050500000005',
    'tanggal_lahir' => '1999-08-14',
    'nama'          => 'Nadya Kusuma',
    'sekolah'       => 'SMP Negeri 1 Pontianak',
    'email'         => 'nadya.kusuma@gmail.com',
    'kota'          => 'Pontianak',
    'provinsi'      => 'Kalimantan Barat',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '5201060600000006',
    'tanggal_lahir' => '1994-01-30',
    'nama'          => 'Hendra Wijaya',
    'sekolah'       => 'SD Negeri 3 Denpasar',
    'email'         => 'hendra.wijaya@gmail.com',
    'kota'          => 'Denpasar',
    'provinsi'      => 'Bali',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '7101070700000007',
    'tanggal_lahir' => '1996-04-18',
    'nama'          => 'Intan Permata',
    'sekolah'       => 'SMA Negeri 2 Manado',
    'email'         => 'intan.permata@gmail.com',
    'kota'          => 'Manado',
    'provinsi'      => 'Sulawesi Utara',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '3201080800000008',
    'tanggal_lahir' => '2001-11-05',
    'nama'          => 'Gilang Ramadhan',
    'sekolah'       => 'SMP Negeri 4 Bogor',
    'email'         => 'gilang.ramadhan@gmail.com',
    'kota'          => 'Bogor',
    'provinsi'      => 'Jawa Barat',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '1112131415161718',
    'tanggal_lahir' => '2000-03-05',
    'nama'          => 'Aaliyah',
    'sekolah'       => 'SMA Kartika',
    'email'         => 'aaliyah@gmail.com',
    'kota'          => 'Bogor',
    'provinsi'      => 'Jawa Barat',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '7201040000000221',
    'tanggal_lahir' => '2000-03-15',
    'nama'          => 'Auroraaa',
    'sekolah'       => 'SMA Kartika',
    'email'         => 'aurora@gmail.com',
    'kota'          => 'Bogor',
    'provinsi'      => 'Jawa Barat',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '0303123400000003',
    'tanggal_lahir' => '2000-03-03',
    'nama'          => 'Jasmine',
    'sekolah'       => 'SMA Pembangunan Jaya',
    'email'         => 'jasmine@gmail.com',
    'kota'          => 'Jakarta',
    'provinsi'      => 'DKI Jakarta',
    'status'        => 'pending',
    'password'      => null,
],
[
    'nuptk'         => '0202123400000002',
    'tanggal_lahir' => '2000-02-02',
    'nama'          => 'Regina',
    'sekolah'       => 'SMA Pembangunan Jaya',
    'email'         => 'regina@gmail.com',
    'kota'          => 'Jakarta',
    'provinsi'      => 'DKI Jakarta',
    'status'        => 'pending',
    'password'      => null,
],
            [
                'nuptk'         => '1122334455667788',
                'tanggal_lahir' => '1995-03-08',
                'nama'          => 'Ahmad Fauzi',
                'sekolah'       => 'SD Negeri 5 Surabaya',
                'email'         => 'ahmad@gmail.com',
                'kota'          => 'Surabaya',
                'provinsi'      => 'Jawa Timur',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '2005050500000001',
                'tanggal_lahir' => '2005-05-05',
                'nama'          => 'Aqeela',
                'sekolah'       => 'SMA Negeri 2 Jakarta',
                'email'         => 'aqeela@gmail.com',
                'kota'          => 'Jakarta',
                'provinsi'      => 'DKI Jakarta',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '2004040400000002',
                'tanggal_lahir' => '2004-04-04',
                'nama'          => 'Aurela',
                'sekolah'       => 'SMA Negeri 5 Bandung',
                'email'         => 'aurela@gmail.com',
                'kota'          => 'Bandung',
                'provinsi'      => 'Jawa Barat',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '2222000000003333',
                'tanggal_lahir' => '2003-03-03',
                'nama'          => 'Vanessa',
                'sekolah'       => 'SMA Negeri 1 Yogyakarta',
                'email'         => 'vanessa@gmail.com',
                'kota'          => 'Yogyakarta',
                'provinsi'      => 'Daerah Istimewa Yogyakarta (DIY)',
                'status'        => 'pending',
                'password'      => null,
            ],
            // ── 3 data dummy tambahan ──
            [
                'nuptk'         => '3301010100000001',
                'tanggal_lahir' => '1992-07-17',
                'nama'          => 'Budi Santoso',
                'sekolah'       => 'SMP Negeri 2 Semarang',
                'email'         => 'budi.santoso@gmail.com',
                'kota'          => 'Semarang',
                'provinsi'      => 'Jawa Tengah',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '3401020200000002',
                'tanggal_lahir' => '1997-09-25',
                'nama'          => 'Dewi Lestari',
                'sekolah'       => 'SMA Negeri 3 Medan',
                'email'         => 'dewi.lestari@gmail.com',
                'kota'          => 'Medan',
                'provinsi'      => 'Sumatera Utara',
                'status'        => 'pending',
                'password'      => null,
            ],
            [
                'nuptk'         => '6401030300000003',
                'tanggal_lahir' => '1993-12-10',
                'nama'          => 'Rizky Pratama',
                'sekolah'       => 'SD Negeri 1 Makassar',
                'email'         => 'rizky.pratama@gmail.com',
                'kota'          => 'Makassar',
                'provinsi'      => 'Sulawesi Selatan',
                'status'        => 'pending',
                'password'      => null,
            ],
        ];

        foreach ($data as $item) {
            Peserta::updateOrCreate(
                ['nuptk' => $item['nuptk']],
                $item
            );
        }
    }
}